# Generated by Django 5.1.5 on 2025-01-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('student_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd', models.CharField(max_length=8, unique=True)),
                ('toan', models.FloatField(blank=True, null=True)),
                ('ngu_van', models.FloatField(blank=True, null=True)),
                ('ngoai_ngu', models.FloatField(blank=True, null=True)),
                ('vat_li', models.FloatField(blank=True, null=True)),
                ('hoa_hoc', models.FloatField(blank=True, null=True)),
                ('sinh_hoc', models.FloatField(blank=True, null=True)),
                ('lich_su', models.FloatField(blank=True, null=True)),
                ('dia_li', models.FloatField(blank=True, null=True)),
                ('gdcd', models.FloatField(blank=True, null=True)),
                ('ma_ngoai_ngu', models.CharField(blank=True, max_length=2, null=True)),
                ('tong_a00', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sbd'], name='students_st_sbd_dccac6_idx')],
            },
        ),
    ]
